### ISSUE TITLE
Simulator needs to handle partial OPC messages

### ISSUE THREAD

**Issue by jobevers** [house-of-enlightenment/house-of-enlightenment#41]
![image](https://user-images.githubusercontent.com/2380127/29183599-471b79e6-7dd1-11e7-8202-89b04d1abb03.png)

I noticed some odd blinking in the simulator and so added some logging.  What happens is that sometimes the nodejs server recieves a partial opc message on the socket and then passes that along over the websocket.

What it should do is check the expected length of the message, compare it to the actual length of message and wait for more data if it needs to.  Then, when it has all of the data, pass that along to the websocket.

**Comment by jobevers** [comment]
@lax4mike see https://github.com/house-of-enlightenment/house-of-enlightenment/commit/f3112b5966f8c8b44039e35e02089841325b4e2d for the commit that adds logging

**Comment by lax4mike** [comment]
@jobevers is this resolved by dropping those frames?
