### ISSUE TITLE
Add to layout - address

### ISSUE THREAD

**Issue by anthonyn** [house-of-enlightenment/house-of-enlightenment#5]
We need to add the address for each ledscape server to the layout. 

This will probably be 
10.0.0.32 - first 48 strips
10.0.0.33 - next 48 strips
10.0.0.34 - final 36 strips

**Comment by lax4mike** [comment]
Update to use 4 addresses:

0-35 = 10.0.0.32
36-71 = 10.0.0.33
72-107 = 10.0.0.34
108-131 = 10.0.0.35
